[package]
name = "sim-proto"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.13"
tonic = { version = "0.12", features = ["transport"] }

[build-dependencies]
protoc-bin-vendored = "3"
tonic-build = "0.12"
